# these values are required by helmfile-base.yaml.gotmpl releases
nuxeo:
  enabled: true
mongodb:
  enabled: true
postgresql:
  enabled: false
opensearch:
  enabled: true
kafka:
  enabled: true

# values definition
