repositories:
  - name: bitnami
    url: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  - name: elastic
    url: https://helm.elastic.co/
  - name: opensearch
    url: https://opensearch-project.github.io/helm-charts/
  - name: nuxeo
    url: https://chartmuseum.platform.dev.nuxeo.com/

helmDefaults:
  timeout: 300
  wait: true

releases:
  - name: nuxeo
    chart: nuxeo/nuxeo
    version: 3.0.11
    needs:
      - {{ eq .Environment.Name "functional-tests-2023" | ternary "opensearch" "elasticsearch" }}
      - {{ eq .Environment.Name "functional-tests-2023" | ternary "mongodb6" "mongodb4" }}
    values:
      - values/values-nuxeo.yaml.gotmpl
      - values/values-tolerations.yaml.gotmpl
  - name: elasticsearch
    chart: elastic/elasticsearch
    condition: elasticsearch.enabled
    version: 7.9.2
    values:
      - values/values-elasticsearch.yaml.gotmpl
      - values/values-tolerations.yaml.gotmpl
  - name: opensearch
    chart: opensearch/opensearch
    condition: opensearch.enabled
    version: 1.16.0
    values:
      - values/values-opensearch.yaml.gotmpl
      - values/values-tolerations.yaml.gotmpl
  - name: mongodb4
    chart: bitnami/mongodb
    condition: mongodb4.enabled
    version: 7.14.2
    values:
      - values/values-mongodb-4.yaml.gotmpl
      - values/values-mongodb-commons.yaml.gotmpl
      - values/values-tolerations.yaml.gotmpl
  - name: mongodb6
    chart: bitnami/mongodb
    condition: mongodb6.enabled
    version: 13.3.1
    values:
      - values/values-mongodb-6.yaml.gotmpl
      - values/values-mongodb-commons.yaml.gotmpl
      - values/values-tolerations.yaml.gotmpl

environments:
  functional-tests-10.10:
    values:
      - environments/functional-tests-1010.yaml
      - nuxeo:
          image:
            tag: {{ env "NUXEO_VERSION" | default "10.10" | quote }}
        elasticsearch:
          imageTag: "6.8.23"
        mongodb:
          image:
            tag: "4.2"
  functional-tests-2021:
    values:
      - environments/functional-tests-2021.yaml
      - nuxeo:
          image:
            tag: {{ env "NUXEO_VERSION" | default "2021" | quote }}
        elasticsearch:
          imageTag: "7.9.2"
        mongodb:
          image:
            tag: "4.4"
  functional-tests-2023:
    values:
      - environments/functional-tests-2023.yaml
      - nuxeo:
          image:
            tag: {{ env "NUXEO_VERSION" | default "2023" | quote }}
        opensearch:
          image:
            tag: "1.3.6"
        mongodb:
          image:
            tag: "6.0.2"
