name: Bot Auto Merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    uses: nuxeo/gh-build-tools/.github/workflows/bot-auto-merge.yml@f80fef104d7826271d9ea294787eca6557e57d88 # v0.20.0
