name: Bot Auto Merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    uses: nuxeo/gh-build-tools/.github/workflows/bot-auto-merge.yml@369e9f656fb2eedd24d5fcdcb64bb98cff68b98f # v0.21.0
